create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text check (char_length(display_name) <= 60),
  avatar_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.fortune_draws (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  source_key text not null,
  fortune_id smallint not null check (fortune_id between 1 and 64),
  drawn_on date not null,
  drawn_at timestamptz not null default now(),
  snapshot jsonb not null default '{}'::jsonb,
  constraint fortune_draws_user_source_unique unique (user_id, source_key)
);

create index fortune_draws_user_date_idx
  on public.fortune_draws (user_id, drawn_on desc, drawn_at desc);

alter table public.profiles enable row level security;
alter table public.fortune_draws enable row level security;

create policy "Users can read their own profile"
  on public.profiles for select
  to authenticated
  using ((select auth.uid()) = id);

create policy "Users can create their own profile"
  on public.profiles for insert
  to authenticated
  with check ((select auth.uid()) = id);

create policy "Users can update their own profile"
  on public.profiles for update
  to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

create policy "Users can delete their own profile"
  on public.profiles for delete
  to authenticated
  using ((select auth.uid()) = id);

create policy "Users can read their own fortune draws"
  on public.fortune_draws for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can create their own fortune draws"
  on public.fortune_draws for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create policy "Users can update their own fortune draws"
  on public.fortune_draws for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "Users can delete their own fortune draws"
  on public.fortune_draws for delete
  to authenticated
  using ((select auth.uid()) = user_id);

grant usage on schema public to authenticated;
grant select, insert, update, delete on table public.profiles to authenticated;
grant select, insert, update, delete on table public.fortune_draws to authenticated;
grant usage, select on sequence public.fortune_draws_id_seq to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'user-assets',
  'user-assets',
  false,
  2097152,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "Users can read their own files"
  on storage.objects for select
  to authenticated
  using (
    bucket_id = 'user-assets'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

create policy "Users can upload their own files"
  on storage.objects for insert
  to authenticated
  with check (
    bucket_id = 'user-assets'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

create policy "Users can update their own files"
  on storage.objects for update
  to authenticated
  using (
    bucket_id = 'user-assets'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  )
  with check (
    bucket_id = 'user-assets'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

create policy "Users can delete their own files"
  on storage.objects for delete
  to authenticated
  using (
    bucket_id = 'user-assets'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );
